version: 2
updates:
  # ============================================
  # npm dependencies
  # ============================================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maherhany1010-beep"
    assignees:
      - "maherhany1010-beep"
    labels:
      - "dependencies"
      - "automated"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific packages if needed
    ignore:
      # Example: ignore major updates for specific packages
      # - dependency-name: "next"
      #   update-types: ["version-update:semver-major"]
    
  # ============================================
  # GitHub Actions
  # ============================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maherhany1010-beep"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

